# Generated by Django 3.2.18 on 2023-03-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeTable',
            fields=[
                ('like_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'like_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
