# Generated by Django 3.2.18 on 2023-03-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20230324_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCat',
            fields=[
                ('food_cat_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'food_cat',
                'managed': False,
            },
        ),
    ]
