# Generated by Django 3.2.18 on 2023-03-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_foodcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientRec',
            fields=[
                ('nutrient_rec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nutrient_rec',
                'managed': False,
            },
        ),
    ]
